
-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `to_chuc_dao_tao`
--

CREATE TABLE `to_chuc_dao_tao` (
  `To_Chuc_Dao_Tao_ID` int(11) NOT NULL,
  `Ma_To_Chuc_Dao_Tao` varchar(255) CHARACTER SET utf8 COLLATE utf8_vietnamese_ci NOT NULL,
  `Ten_To_Chuc_Dao_Tao` varchar(255) CHARACTER SET utf8 COLLATE utf8_vietnamese_ci NOT NULL,
  `Logo` varchar(255) NOT NULL,
  `Website` varchar(255) NOT NULL,
  `Thong_Tin_Tuyen_Sinh` varchar(255) NOT NULL,
  `Rankiing` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Đang đổ dữ liệu cho bảng `to_chuc_dao_tao`
--

INSERT INTO `to_chuc_dao_tao` (`To_Chuc_Dao_Tao_ID`, `Ma_To_Chuc_Dao_Tao`, `Ten_To_Chuc_Dao_Tao`, `Logo`, `Website`, `Thong_Tin_Tuyen_Sinh`, `Rankiing`) VALUES
(1, 'BKA', 'Đại học Bách Khoa Hà Nội', 'img/bkhnlogo.jpg', 'https://www.hust.edu.vn/', 'http://tuyensinhdaihoc.hust.edu.vn/', 1),
(2, 'QH', 'Đại học Quốc gia Hà Nội', 'img/dhqghnlogo.jpg', 'http://www.vnu.edu.vn/home/', 'http://tuyensinh.vnu.edu.vn/', 2),
(3, 'SPH', 'Đại học Sư phạm Hà Nội', 'img/dhsphnlogo.jpg', 'http://hnue.edu.vn/', 'http://hnue.edu.vn/Tintuc-Sukien/Trangtintonghop/tabid/260/category/61/Default.aspx', 3),
(4, 'TCT', 'Đại học Cần Thơ', 'img/dhctlogo.jpg', 'https://www.ctu.edu.vn/', 'https://tuyensinh.ctu.edu.vn/', 4),
(5, 'QS', 'Đại học Quốc Gia Thành Phố Hồ Chí Minh', 'img/dhqgtphcmlogo.jpg', 'http://www.vnuhcm.edu.vn/', 'http://tuyensinh.vnuhcm.edu.vn/', 5),
(6, 'HVN', 'Học viện Nông Nghiệp Việt Nam', 'img/hvnnvnlogo.jpg', 'http://www.vnua.edu.vn/', 'http://tuyensinh.vnua.edu.vn/', 6),
(7, 'MDA', 'Đại học Mỏ - Địa Chất', 'img/dhmdclogo.jpg', 'http://humg.edu.vn/Pages/home.aspx', 'http://ts.humg.edu.vn/Pages/home.aspx', 7),
(8, 'DT', 'Đại học Thái Nguyên', 'img/dhtnlogo.jpg', 'http://www.tnu.edu.vn/Pages/home.aspx', 'http://tuyensinh.tnu.edu.vn/', 8),
(9, 'DD', 'Đại học Đà Nẵng', 'img/dhdnlogo.jpg', 'http://www.udn.vn/', 'http://ts.udn.vn/', 9),
(10, 'YHB', 'Đại học Y Hà Nội', 'img/dhyhnlogo.jpg', 'http://www.hmu.edu.vn/news/default.aspx', 'http://www.hmu.edu.vn/news/xc66_Tuyen-sinh-.html', 10),
(11, 'NLS', 'Đại học Nông Lâm Thành Phố Hồ Chí Minh', 'img/dhnltphcmlogo.jpg', 'http://www.hcmuaf.edu.vn/', 'http://ts.hcmuaf.edu.vn/contents.php?ur=ts&ids=32054', 11),
(12, 'BVH', 'Học viện Công nghệ Bưu chính Viễn thông', 'img/dhcnbcvtlogo.jpg', 'http://portal.ptit.edu.vn/', 'http://portal.ptit.edu.vn/tuyensinh/dh-chinh-quy/', 12),
(13, 'DH', 'Đại học Huế', 'img/dhhlogo.jpg', 'http://hueuni.edu.vn/', 'http://hueuni.edu.vn/portal/vi/index.php/Category/tin-tuyen-sinh.html', 13),
(14, 'KHA', 'Đại học Kinh tế Quốc dân', 'img/dhktqdlogo.jpg', 'https://www.neu.edu.vn/', 'https://tuyensinh.neu.edu.vn/', 14),
(15, 'GHA', 'Đại học Giao Thông Vận tải', 'img/dhgtvtlogo.jpg', 'https://www.utc.edu.vn/', 'http://ts.utc.edu.vn/', 15),
(16, 'TDV', 'Đại học Vinh', 'img/dhvlogo.jpg', 'http://www.vinhuni.edu.vn/', 'http://www.vinhuni.edu.vn/tuyen-sinh/dai-hoc-chinh-quy', 16),
(17, 'KQH', 'Học viện Kỹ thuật Quân sự', 'img/hvktqslogo.jpg', 'http://mta.edu.vn/', 'http://mta.edu.vn/TUY%E1%BB%82N-SINH/Tuy%E1%BB%83n-sinh-%C4%91%E1%BA%A1i-h%E1%BB%8Dc', 17),
(18, 'DQN', 'Đại học Quy Nhơn', 'img/dhqnlogo.jpg', 'http://www.qnu.edu.vn/', 'http://tuyensinh.qnu.edu.vn/', 18),
(19, 'DVT', 'Đại học Trà Vinh', 'img/dhtvlogo.jpg', 'http://www.tvu.edu.vn/', 'https://tuyensinh.tvu.edu.vn/', 19),
(20, 'XDA', 'Đại học Xây Dựng', 'img/dhxdlogo.jpg', 'http://nuce.edu.vn/', 'http://tuyensinh.nuce.edu.vn/', 20),
(21, 'TSN', 'Đại học Nha Trang', 'img/dhntlogo.jpg', 'http://www.ntu.edu.vn/', 'http://tuyensinh.ntu.edu.vn/', 21),
(22, 'KSA', 'Đại học Kinh tế Thành phố Hồ Chí Minh', 'img/dhkttphcmlogo.jpg', 'http://www.ueh.edu.vn/', 'http://tuyensinh.ueh.edu.vn/', 22),
(23, 'QSQ', 'Đại học Quốc tế - Đại học Quốc gia Thp. Hồ Chí Minh', 'img/dhqtdhqgtphcmlogo.jpg', 'https://www.hcmiu.edu.vn/', 'https://tuyensinh.hcmiu.edu.vn/', 23),
(24, 'DDT', 'Đại học Duy Tân', 'img/dhdtlogo.jpg', 'http://duytan.edu.vn/', 'http://duytan.edu.vn/tuyen-sinh/Page/Home.aspx', 24),
(25, 'QST', 'Đại học Khoa Học Tự Nhiên - Đại học Quốc Gia Thp. Hồ Chí Minh', 'img/dhkhtndhqgtphcmlogo.jpg', 'https://www.hcmus.edu.vn/', 'https://tuyensinh.hcmus.edu.vn/', 25),
(26, 'DVL', 'Đại học Văn Lang', 'img/dhvllogo.jpg', 'http://www.vanlanguni.edu.vn/', 'http://tuyensinh.vanlanguni.edu.vn/', 26),
(27, 'RMU', 'Đại học Quốc tế RMIT Việt Nam', 'img/dhqtrmitvnlogo.jpg', 'https://www.rmit.edu.vn/vi', 'http://diemthi.tuyensinh247.com/thong-tin-dai-hoc-quoc-te-rmit-viet-nam-RMU.html', 27),
(28, 'FPT', 'Đại học FPT', 'img/dhfptlogo.jpg', 'http://fpt.edu.vn/don-vi/dai-hoc-fpt', 'http://fpt.edu.vn/don-vi/dai-hoc-fpt', 28),
(29, 'QSC', 'Đại học Công nghệ Thông tin - Đại học Quốc gia Thành phố Hồ Chí Minh', 'img/dhcnttdhqgtphcmlogo.jpg', 'https://www.uit.edu.vn/', 'https://tuyensinh.uit.edu.vn/', 29),
(30, 'YDS', 'Đại học Y dược Thành phố Hồ Chí Minh', 'img/dhydtphcmlogo.jpg', 'http://www.yds.edu.vn/yds2/', 'http://www.yds.edu.vn/yds2/?Content=tuyensinh', 30),
(31, 'DKC', 'Đại học Công nghệ Thp. Hồ Chí Minh', 'img/dhcntphcmlogo.jpg', 'https://www.hutech.edu.vn/', 'http://www.hutech.edu.vn/xet-tuyen-dai-hoc', 31),
(32, 'SPK', 'Đại học Sư phạm Kỹ thuật TP. Hồ Chí Minh', 'img/dhspkttphcmlogo.jpg', 'http://hcmute.edu.vn/', 'http://hcmute.edu.vn/ArticleId/9333f78d-088e-49e5-9a65-1e93a6404c9d/tuyen-sinh-dai-hoc-he-chinh-quy-nam-2018-cua-truong-dh-spkt-tp-hcm', 32),
(33, 'TAG', 'Đại học An Giang', 'img/dhaglogo.jpg', 'http://www.agu.edu.vn/', 'http://www.agu.edu.vn/tuyensinh/', 33),
(34, 'SKH', 'Đại học Sư phạm Kỹ thuật Hưng Yên', 'img/dhspkthylogo.jpg', 'http://www.utehy.edu.vn/', 'http://tuyensinh.utehy.edu.vn/', 34),
(35, 'SPS', 'Đại học Sư phạm TP. HỒ CHÍ MINH', 'img/dhsptphcmlogo.jpg', 'http://www.hcmup.edu.vn/', 'http://www.thongtintuyensinh.vn/Truong_Dai_hoc_Su_pham_TPHCM_C51_D705.htm', 35),
(36, 'NTH', 'Đại học Ngoại thương', 'img/dhngoaithuonglogo.jpg', 'http://ftu.edu.vn/', 'http://www.tuyensinhtoanquoc24h.com/2017/11/truong-dai-hoc-ngoai-thuong-tuyen-sinh.html', 36),
(37, 'NHH', 'Học viện Ngân hàng', 'img/hvnhlogo.jpg', 'http://hvnh.edu.vn/hvnh/vi/home.html', 'http://hvnh.edu.vn/hvnh/vi/thong-tin-tuyen-sinh', 37),
(38, 'DTH', 'Đại học Hoa Sen', 'img/dhhslogo.jpg', 'https://www.hoasen.edu.vn/vi', 'https://tuyensinh.hoasen.edu.vn/', 38),
(39, 'HHA', 'Đại học Hàng hải Việt Nam', 'img/dhhhvnlogo.jpg', 'http://www.vimaru.edu.vn/', 'http://tuyensinh.vimaru.edu.vn/', 39),
(40, 'VGU', 'Đại học Việt - Đức', 'img/dhvdlogo.jpg', 'http://www.vgu.edu.vn/vi/', 'http://www.vgu.edu.vn/vi/web/cms/admission', 40),
(41, 'NTT', 'Đại học Nguyễn Tất Thành', 'img/dhnttlogo.jpg', 'http://ntt.edu.vn/web/', 'http://ntt.edu.vn/web/tuyen-sinh/', 41),
(42, 'HDT', 'Đại học Hồng Đức', 'img/dhhdlogo.jpg', 'http://www.hdu.edu.vn/default.aspx', 'http://www.hdu.edu.vn/default.aspx', 42),
(43, 'MBS', 'Đại học Mở Thành phố Hồ Chí Minh', 'img/dhmtphcmlogo.jpg', 'http://ou.edu.vn/', 'http://tuyensinh.ou.edu.vn/', 43),
(44, 'DLH', 'Đại học Lạc Hồng', 'img/dhlhlogo.jpg', 'https://lhu.edu.vn/', 'https://tuyensinh.lhu.edu.vn/', 44),
(45, '', 'Cao đẳng Nghề Bách Khoa Hà Nội', 'img/bkhnlogo.jpg', 'http://www.hactech.edu.vn/', 'http://www.hactech.edu.vn/vn/Thong-tin-tuyen-sinh-517.html', 45),
(46, 'YTC', 'Đại học Y tế Công cộng', 'img/dhytcclogo.jpg', 'http://www.huph.edu.vn/', 'http://tuyensinh.huph.edu.vn/', 46),
(47, 'DHP', 'Đại học Dân lập Hải Phòng', 'img/dhdlhplogo.jpg', 'http://www.hpu.edu.vn/home/trangchu.html', 'http://www.hpu.edu.vn/tuyensinh/HPUTS-tuyensinh.html', 47),
(48, 'DDL', 'Đại học Điện lực', 'img/dhdllogo.jpg', 'http://epu.edu.vn/', 'http://tuyensinh.epu.edu.vn/', 48),
(49, 'DTN', 'Đại học Nông Lâm Thái Nguyên', 'img/dhnltnlogo.jpg', 'http://tuaf.edu.vn/', 'http://tuyensinh.tuaf.edu.vn/', 49),
(50, 'SP2', 'Đại học Sư phạm Hà Nội 2', 'img/dhsphn2logo.jpg', 'http://www.hpu2.edu.vn/', 'http://tuyensinh.hpu2.edu.vn/', 50),
(51, 'DTK', 'Đại học Kỹ thuật Công nghiệp - Đại học Thái Nguyên', 'img/dhktcntnlogo.jpg', 'http://www.tnut.edu.vn/', 'http://ts.tnut.edu.vn/', 51),
(52, 'QSX', 'Đại học Khoa học Xã hội và Nhân văn - Đại học Quốc gia Thành phố Hồ Chí Minh', 'img/dhkhxhvnvdhqgtphcmlogo.jpg', 'http://hcmussh.edu.vn/', 'http://tuyensinh.hcmussh.edu.vn/', 52),
(53, 'DCN', 'Đại học Công nghiệp Hà Nội', 'img/dhcnhnlogo.jpg', 'https://www.haui.edu.vn/vn', 'https://tuyensinh.haui.edu.vn/', 53),
(54, 'SGD', 'Đại học Sài Gòn', 'img/dhsglogo.jpg', 'https://sgu.edu.vn/', 'http://www.thongtintuyensinh.vn/Truong-Dai-hoc-Sai-Gon_C51_D707.htm', 54),
(55, 'TLA', 'Đại học Thủy lợi', 'img/dhtllogo.jpg', 'http://www.tlu.edu.vn/', 'http://www.tlu.edu.vn/tuyen-sinh', 55),
(56, 'GTA', 'Đại học Công nghệ Giao thông Vận tải', 'img/dhcngtvtlogo.jpg', 'http://utt.edu.vn/', 'http://tuyensinh.utt.edu.vn/', 56),
(57, 'SPD', 'Đại học Đồng Tháp', 'img/dhdongthaplogo.jpg', 'http://www.dthu.edu.vn/', 'http://www.dthu.edu.vn/', 57),
(58, 'LNS', 'Đại học Lâm nghiệp', 'img/dhlnlogo.jpg', 'http://vnuf.edu.vn/', 'http://tuyensinh.vfu.edu.vn/', 58),
(59, 'VHH', 'Đại học Văn hóa Hà Nội', 'img/dhvhhnlogo.jpg', 'http://huc.edu.vn/', 'http://huc.edu.vn/thong-tin-tuyen-sinh-dai-hoc-chinh-quy-nam-2018-5311-vi.htm', 59),
(60, 'LPS', 'Đại học Luật TP.HCM', 'img/dhltphcmlogo.jpg', 'http://www.hcmulaw.edu.vn/', 'http://ts.hcmulaw.edu.vn/', 60),
(61, 'NHS', 'Đại học Ngân hàng Thành phố Hồ Chí Minh', 'img/dhnhtphcmlogo.jpg', 'http://buh.edu.vn/', 'http://tuyensinh.buh.edu.vn/', 61),
(62, 'DTT', 'Đại học Tôn Đức Thắng', 'img/dhtdtlogo.jpg', 'http://www.tdtu.edu.vn/', 'http://tuyensinh.tdtu.edu.vn/', 62),
(63, 'TTB', 'Đại học Tây Bắc', 'img/dhtblogo.jpg', 'http://www.utb.edu.vn/', 'http://www.utb.edu.vn/index.php/tuyen-sinh', 63),
(64, 'HUI', 'Đại học Công nghiệp TP.HCM', 'img/dhcongnghieptphcmlogo.jpg', 'http://www.hui.edu.vn/', 'http://www.utb.edu.vn/index.php/tuyen-sinh', 64),
(65, 'DKH', 'Đại học Dược Hà Nội', 'img/dhdhnlogo.jpg', 'http://www.hup.edu.vn/Pages/default.aspx#section=generalw', 'http://www.hup.edu.vn/Pages/tuyen-sinh.aspx', 65),
(66, 'TYS', 'Đại học Y khoa Phạm Ngọc Thạch', 'img/dhykpntlogo.jpg', 'https://www.pnt.edu.vn/', 'https://pqldt.pnt.edu.vn/vi/tuyen-sinh-dai-hoc-chinh-quy', 66),
(67, 'NHF', 'Đại học Hà Nội', 'img/dhhnlogo.jpg', 'http://www.hanu.edu.vn/vn/', 'http://hanu.vn/vn/chinh-quy.html', 67),
(68, 'KTS', 'Đại học Kiến trúc TP. Hồ Chí Minh', 'img/dhkientructphcmlogo.jpg', 'http://www.uah.edu.vn/', 'http://www.uah.edu.vn/router/dai-hoc-353.html', 68),
(69, 'HTC', 'Học viện Tài chính', 'img/hvtclogo.jpg', 'https://hvtc.edu.vn/', 'https://hvtc.edu.vn/tabid/109/Default.aspx', 69),
(70, 'TDL', 'Đại học Đà Lạt', 'img/dhdalatlogo.jpg', 'http://www.dlu.edu.vn/', 'http://pqldt.dlu.edu.vn/', 70),
(71, 'QSK', 'Đại học Kinh tế Luật - Đại học Quốc gia Thành phố Hồ Chí Minh', 'img/dhktldhqgtphcmlogo.jpg', 'http://www.uel.edu.vn/', 'http://tuyensinh.uel.edu.vn/', 71),
(72, 'QHT', 'Đại học Khoa học Tự nhiên - Đại học Quốc gia Hà Nội', 'img/dhkhtndhqghnlogo.jpg', 'http://hus.vnu.edu.vn/', 'http://hus.vnu.edu.vn/vi/main/tuyensinh', 72),
(73, 'LPH', 'Đại học Luật Hà Nội', 'img/dhlhnlogo.jpg', 'http://hlu.edu.vn/', 'http://tuyensinh.hlu.edu.vn/', 73),
(74, 'MHN', 'Viện đại học Mở Hà Nội', 'img/dhmhnlogo.jpg', 'https://hou.edu.vn/', 'https://tuyensinh.hou.edu.vn/', 74),
(75, 'QHE', 'Đại học Kinh tế - Đại học Quốc gia Hà Nội', 'img/dhktdhqghnlogo.jpg', 'http://ueb.edu.vn/', 'http://tuyensinhdaihoc.ueb.edu.vn/', 75),
(76, 'TDM', 'Đại học Thủ Dầu Một', 'img/dhtdmlogo.jpg', 'https://tdmu.edu.vn/', 'https://tuyensinh.tdmu.edu.vn/', 76),
(77, 'DNT', 'Đại học Ngoại ngữ - Tin học TP.HCM', 'img/dhnnthtphcmlogo.jpg', 'http://www.huflit.edu.vn/', 'http://www.huflit.edu.vn/tuyen-sinh-39/', 77),
(78, 'KTA', 'Đại học Kiến trúc Hà Nội', 'img/dhkthnlogo.jpg', 'http://www.hau.edu.vn/', 'http://www.hau.edu.vn/thong-tin-tuyen-sinh-dai-hoc_c08/', 78),
(79, '', 'Trung tâm Nghiên cứu và Đào tạo Thiết kế Vi mạch', 'img/icdreclogo.jpg', 'http://icdrec.edu.vn/', '', 79),
(80, 'TMA', 'Đại học Thương mại', 'img/dhtmlogo.jpg', 'http://tmu.edu.vn/', 'https://tmu.edu.vn/vi/news/TUYEN-SINH/', 80),
(81, 'THP', 'Đại học Hải Phòng', 'img/dhhplogo.jpg', 'http://dhhp.edu.vn/vi/trang-chu/', 'http://tuyensinh.dhhp.edu.vn/', 81),
(82, '', 'Viện đào tạo Quốc tế về Khoa học Vật liệu Đại học Bách Khoa Hà Nội', 'img/itimslogo.jpg', 'http://www.itims.edu.vn/', '', 82),
(83, 'DTL', 'Đại học Thăng Long', 'img/dhthanglonglogo.jpg', 'http://www.thanglong.edu.vn/', 'http://www.thanglong.edu.vn/tuyen-sinh/tuyen-sinh-dai-hoc-chinh-quy', 83),
(84, 'YPB', 'Đại học Y Dược Hải Phòng', 'img/dhydhplogo.jpg', 'http://hpmu.edu.vn/hpmu/', 'http://hpmu.edu.vn/hpmu/news/THONG-TIN-TUYEN-SINH/', 84),
(85, 'DQK', 'Đại học Kinh doanh và Công nghệ Hà Nội', 'img/dhkdvcnhnlogo.jpg', 'http://hubt.edu.vn/', 'http://hubt.edu.vn/tin-tuc-khoa-1/dai-hoc-chinh-quy/20', 85),
(86, 'GTS', 'Đại học Giao thông Vận tải Thành phố Hồ Chí Minh', 'img/dhgtvttphcmlogo.jpg', 'https://ut.edu.vn/', 'http://tuyensinh.ut.edu.vn/chuyenmuc/thong-bao-tuyen-sinh/dai-hoc-cao-dang-chinh-quy/', 86),
(87, 'DSG', 'Đại học Công nghệ Sài Gòn', 'img/dhcnsglogo.jpg', 'http://www.stu.edu.vn/', 'http://www.stu.edu.vn/vi/1/14112/thong-bao-tuyen-sinh-dai-hoc-chinh-quy-nam-2018.html', 87),
(88, 'DBD', 'Đại học Bình Dương', 'img/dhbdlogo.jpg', 'http://www.bdu.edu.vn/', 'http://tuyensinh.bdu.edu.vn/', 88),
(89, 'HQT', 'Học viện Ngoại giao Việt Nam', 'img/hvnglogo.jpg', 'http://www.dav.edu.vn/', 'https://www.dav.edu.vn/vi/tuyen-sinh', 89),
(90, '', 'Học viện Kỹ thuật Lê Qúy Đôn', 'img/dhktlqdlogo.jpg', 'http://www.lqdtu.edu.vn/', '', 90),
(91, 'DHL', 'Đại học Nông Lâm - Đại học Huế', 'img/dhnlhlogo.jpg', 'http://www.huaf.edu.vn/', 'http://tuyensinh.huaf.edu.vn/', 91),
(92, 'BVU', 'Đại học Bà Rịa - Vũng Tàu', 'img/dhbrvtlogo.jpg', 'http://bvu.edu.vn/', 'http://bvu.edu.vn/tuyen-sinh1', 92),
(93, 'DQB', 'Đại học Quảng Bình', 'img/dhqblogo.jpg', 'http://quangbinhuni.edu.vn/', 'http://quangbinhuni.edu.vn/Dai-Hoc-Quang-Binh/PortalNews/Tuyen_sinh/0/36/0', 94),
(94, 'HIU', 'Đại học Quốc tế Hồng Bàng', 'img/dhqthblogo.jpg', 'http://hiu.vn/', 'http://admissions.hiu.vn/', 95),
(95, 'DCD', 'Đại học Công nghệ Đồng Nai', 'img/dhcndnlogo.jpg', 'http://dntu.edu.vn/', 'http://ts.dntu.edu.vn/', 96),
(96, 'TTN', 'Đại học Tây Nguyên', 'img/dhtaynguyenlogo.jpg', 'http://www.ttn.edu.vn/', 'https://www.ttn.edu.vn/index.php/tuyensinh/tuyensinhdhcd', 97),
(97, '', 'Saigon Tech', 'img/saigontechlogo.jpg', 'http://www.saigontech.edu.vn/', 'http://www.saigontech.edu.vn/thong-tin-tuyen-sinh-va-nhap-hoc.html', 98),
(98, 'DBG', 'Đại học Nông Lâm Bắc Giang', 'img/dhnlbglogo.jpg', 'http://bafu.edu.vn/home/', 'http://bafu.edu.vn/tuyensinh/', 99),
(99, 'DBH', 'Đại học Quốc tế Bắc Hà', 'img/dhqtbhlogo.jpg', 'http://www.bhiu.edu.vn/', 'http://www.bhiu.edu.vn/danh-muc-tin/313_tuyen-sinh', 100),
(100, 'MTS', 'Đại học Mỹ thuật Thành phố Hồ Chí Minh', 'img/dhmythuattphcmlogo.jpg', 'http://hcmufa.edu.vn/', 'http://hcmufa.edu.vn/tuyen-sinh', 101),
(101, 'D50', 'Cao đẳng Cộng đồng Đồng Tháp', 'img/cdcddtlogo.jpg', 'http://www.dtcc.edu.vn/', 'http://www.dtcc.edu.vn/tuyen_sinh/ch%C3%ADnh-quy/th%C3%B4ng-tin-tuy%E1%BB%83n-sinh-2018.html', 102),
(102, 'HCH', 'Học viện Hành chính Quốc gia', 'img/hvhcqglogo.jpg', 'http://www1.napa.vn/', 'http://www1.napa.vn/bandaotao/category/tuyen-sinh', 103),
(103, 'GSA', 'Đại học Giao thông Vận tải cơ sở 2 phía Nam', 'img/dhgtvtcs2logo.jpg', 'http://utc2.edu.vn/', 'http://tuyensinh.utc2.edu.vn/', 107),
(104, 'DLA', 'Đại học Kinh tế Công nghiệp Long An', 'img/dhktcnlalogo.jpg', 'http://daihoclongan.edu.vn/', 'https://daihoclongan.edu.vn/tin-tuc-su-kien/tin-tuyen-sinh/1349-thong-tin-tuyen-sinh-dai-hoc-chinh-quy-nam-2018.html', 108),
(105, 'DCL', 'Đại học Cửu Long', 'img/dhcllogo.jpg', 'http://www.mku.edu.vn/', 'http://mku.edu.vn/tuyensinh/', 109),
(106, 'NVH', 'Học viện Âm nhạc Quốc gia Việt Nam', 'img/hvanqgvnlogo.jpg', 'http://www.vnam.edu.vn/', 'http://www.vnam.edu.vn/Categories.aspx?lang=&CatID=9', 110),
(107, 'NVS', 'Nhạc viện Thành phố Hồ Chí Minh', 'img/nvtphcmlogo.jpg', 'http://www.hcmcons.vn/', 'http://www.hcmcons.vn/dao-tao/trung-cap-dai-hoc/thong-bao/tuyen-sinh', 111),
(108, '', 'Cao đẳng Kinh tế Tài chính Vĩnh Long', 'img/cdkttcvllogo.jpg', 'http://www.vcef.edu.vn/', 'http://www.vcef.edu.vn/', 112),
(109, 'DQT', 'Đại học Quang Trung', 'img/dhqtlogo.jpg', 'http://www.quangtrung.edu.vn/page/dhqt.php', 'http://www.quangtrung.edu.vn/page/dhqt.php', 114),
(110, 'MTC', 'Đại học Mỹ thuật Công nghiệp Hà Nội', 'img/dhmtcnhnlogo.jpg', 'http://mythuatcongnghiep.edu.vn/', 'http://mythuatcongnghiep.edu.vn/tin-tuc/tuyen-sinh.html', 115),
(111, 'QSB', 'Đại học Bách Khoa Tp. Hồ Chí Minh', 'img/dhbktphcmlogo.jpg', 'http://www.bku.edu.vn/', 'https://kenhtuyensinh.vn/dai-hoc-bach-khoa-tphcm', 116),
(112, 'DVX', 'Đại học Công nghệ Vạn Xuân', 'img/dhcnvxlogo.jpg', 'https://www.vxut.edu.vn/', 'https://www.vxut.edu.vn/home/v1/category/79/', 123),
(113, '', 'Cao đẳng Sư phạm Ninh Thuận', 'img/cdspntlogo.jpg', 'http://www.cdspninhthuan.edu.vn/', 'http://www.cdspninhthuan.edu.vn/', 124),
(114, 'DPD', 'Đại học Dân lập Phương Đông', 'img/dhpdlogo.jpg', 'http://phuongdong.edu.vn/', 'http://phuongdong.edu.vn/tuyensinh.html', 125),
(115, 'DPX', 'Đại học Dân lập Phú Xuân', 'img/dhdlpxlogo.jpg', 'http://www.phuxuanuni.edu.vn/', 'https://drive.google.com/file/d/1pfy_AMtAeODAm2QclQZFLpARmI86yMK-/view', 126),
(116, '0218', 'Trung cấp Phương Nam', 'img/tcpnlogo.jpg', 'http://www.phuongnam-et.edu.vn/index.php?lang=vi', 'http://tuyensinh.phuongnam-et.edu.vn/', 127),
(117, 'HKC', 'Học viện Khoa học và Công nghệ', 'img/hvkhvcnlogo.jpg', 'http://gust.edu.vn/vn', 'http://gust.edu.vn/vn', 128),
(118, 'D54', 'Cao đẳng Kiên Giang', 'img/cdkglogo.jpg', 'http://www.kgtec.edu.vn/', 'http://www.kgc.edu.vn/tuyen-sinh.html', 129);
