
-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `khoi_thi`
--

CREATE TABLE `khoi_thi` (
  `Khoi_Thi_ID` int(11) NOT NULL,
  `Ma_Khoi_Thi_BGD` varchar(255) CHARACTER SET utf8 COLLATE utf8_vietnamese_ci NOT NULL,
  `Mon_Thi_1` varchar(255) CHARACTER SET utf8 COLLATE utf8_vietnamese_ci NOT NULL,
  `Mon_Thi_2` varchar(255) CHARACTER SET utf8 COLLATE utf8_vietnamese_ci NOT NULL,
  `Mon_Thi_3` varchar(255) CHARACTER SET utf8 COLLATE utf8_vietnamese_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Đang đổ dữ liệu cho bảng `khoi_thi`
--

INSERT INTO `khoi_thi` (`Khoi_Thi_ID`, `Ma_Khoi_Thi_BGD`, `Mon_Thi_1`, `Mon_Thi_2`, `Mon_Thi_3`) VALUES
(1, 'A00', 'Toán Học', 'Vật Lí', 'Hóa Học'),
(2, 'A01', 'Toán Học', 'Vật Lí', 'Tiếng Anh'),
(3, 'B00', 'Toán Học', 'Hóa Học', 'Sinh Học'),
(4, 'C00', 'Ngữ Văn', 'Lịch Sử', 'Địa Lý'),
(5, 'D01', 'Ngữ Văn', 'Toán Học', 'Tiếng Anh'),
(6, 'D02', 'Ngữ Văn', 'Toán Học', 'Tiếng Nga'),
(7, 'D03', 'Ngữ Văn', 'Toán Học', 'Tiếng Pháp'),
(8, 'D04', 'Ngữ Văn', 'Toán Học', 'Tiếng Trung'),
(9, 'D05', 'Ngữ Văn', 'Toán Học', 'Tiếng Đức'),
(10, 'D06', 'Ngữ Văn', 'Toán Học', 'Lịch Sử'),
(11, 'A02', 'Toán Học', 'Vật Lí', 'Sinh Học'),
(12, 'A03', 'Toán Học', 'Vật Lí', 'Lịch Sử'),
(13, 'A04', 'Toán Học', 'Vật Lí', 'Địa Lý'),
(14, 'A05', 'Toán Học', 'Hóa Học', 'Lịch Sử'),
(15, 'A06', 'Toán Học', 'Hóa Học', 'Địa Lý'),
(16, 'A07', 'Toán Học', 'Lịch Sử', 'Địa Lý'),
(17, 'A08', 'Toán Học', 'Lịch Sử', 'Giáo Dục Công Dân'),
(18, 'A09', 'Toán Học', 'Địa Lý', 'Giáo Dục Công Dân'),
(19, 'A10', 'Toán Học', 'Vật Lí', 'Giáo Dục Công Dân'),
(20, 'A11', 'Toán Học', 'Hóa Học', 'Giáo Dục Công Dân'),
(21, 'A12', 'Toán Học', 'Khoa Học Tự Nhiên', 'Khoa Học Xã Hội'),
(22, 'A14', 'Toán Học', 'Khoa Học Tự Nhiên', 'Địa Lý'),
(23, 'A15', 'Toán Học', 'Khoa Học Tự Nhiên', 'Lịch Sử'),
(24, 'A16', 'Toán Học', 'Khoa Học Tự Nhiên', 'Ngữ Văn'),
(25, 'A17', 'Toán Học', 'Vật Lí', 'Khoa Học Xã Hội'),
(26, 'A18', 'Toán Học', 'Hóa Học', 'Khoa Học Xã Hội'),
(27, 'B01', 'Toán Học', 'Sinh Học', 'Lịch Sử'),
(28, 'B02', 'Toán Học', 'Sinh Học', 'Địa Lý'),
(29, 'B03', 'Toán Học', 'Sinh Học', 'Ngữ Văn'),
(30, 'B04', 'Toán Học', 'Sinh Học', 'Giáo Dục Công Dân'),
(31, 'B05', 'Toán Học', 'Sinh Học', 'Khoa Học Xã Hội'),
(32, 'B08', 'Toán Học', 'Sinh Học', 'Tiếng Anh'),
(33, 'C01', 'Ngữ Văn', 'Toán Học', 'Vật Lí'),
(34, 'C02', 'Ngữ Văn', 'Toán Học', 'Hóa Học'),
(35, 'C03', 'Ngữ Văn', 'Toán Học', 'Lịch Sử'),
(36, 'C04', 'Ngữ Văn', 'Toán Học', 'Địa Lý'),
(37, 'C05', 'Ngữ Văn', 'Vật Lí', 'Hóa Học'),
(38, 'C06', 'Ngữ Văn', 'Vật Lí', 'Sinh Học'),
(39, 'C07', 'Ngữ Văn', 'Vật Lí', 'Lịch Sử'),
(40, 'C08', 'Ngữ Văn', 'Hóa Học', 'Sinh Học'),
(41, 'C09', 'Ngữ Văn', 'Vật Lí', 'Địa Lý'),
(42, 'C10', 'Ngữ Văn', 'Hóa Học', 'Lịch Sử'),
(43, 'C12', 'Ngữ Văn', 'Sinh Học', 'Lịch Sử'),
(44, 'C13', 'Ngữ Văn', 'Sinh Học', 'Địa Lý'),
(45, 'C14', 'Ngữ Văn', 'Toán Học', 'Giáo Dục Công Dân'),
(46, 'C16', 'Ngữ Văn', 'Vật Lí', 'Giáo Dục Công Dân'),
(47, 'C17', 'Ngữ Văn', 'Hóa Học', 'Giáo Dục Công Dân'),
(48, 'C19', 'Ngữ Văn', 'Lịch Sử', 'Giáo Dục Công Dân'),
(49, 'C20', 'Ngữ Văn', 'Địa Lý', 'Giáo Dục Công Dân'),
(50, 'D07', 'Toán Học', 'Hóa Học', 'Tiếng Anh'),
(51, 'D08', 'Toán Học', 'Sinh Học', 'Tiếng Anh'),
(52, 'D09', 'Toán Học', 'Lịch Sử', 'Tiếng Anh'),
(53, 'D10', 'Toán Học', 'Địa Lý', 'Tiếng Anh'),
(54, 'D11', 'Ngữ Văn', 'Vật Lí', 'Tiếng Anh'),
(55, 'D12', 'Ngữ Văn', 'Hóa Học', 'Tiếng Anh'),
(56, 'D13', 'Ngữ Văn', 'Sinh Học', 'Tiếng Anh'),
(57, 'D14', 'Ngữ Văn', 'Lịch Sử', 'Tiếng Anh'),
(58, 'D15', 'Ngữ Văn', 'Địa Lý', 'Tiếng Anh'),
(59, 'D16', 'Toán Học', 'Địa Lý', 'Tiếng Đức'),
(60, 'D17', 'Toán Học', 'Địa Lý', 'Tiếng Nga'),
(61, 'D18', 'Toán Học', 'Địa Lý', 'Tiếng Nhật'),
(62, 'D19', 'Toán Học', 'Địa Lý', 'Tiếng Pháp'),
(63, 'D20', 'Toán Học', 'Địa Lý', 'Tiếng Trung'),
(64, 'D21', 'Toán Học', 'Hóa Học', 'Tiếng Đức'),
(65, 'D22', 'Toán Học', 'Hóa Học', 'Tiếng Nga'),
(66, 'D23', 'Toán Học', 'Hóa Học', 'Tiếng Nhật'),
(67, 'D24', 'Toán Học', 'Hóa Học', 'Tiếng Pháp'),
(68, 'D25', 'Toán Học', 'Hóa Học', 'Tiếng Trung'),
(69, 'D26', 'Toán Học', 'Vật Lí', 'Tiếng Đức'),
(70, 'D27', 'Toán Học', 'Vật Lí', 'Tiếng Nga'),
(71, 'D28', 'Toán Học', 'Vật Lí', 'Tiếng Nhật'),
(72, 'D29', 'Toán Học', 'Vật Lí', 'Tiếng Pháp'),
(73, 'D30', 'Toán Học', 'Vật Lí', 'Tiếng Trung'),
(74, 'D31', 'Toán Học', 'Sinh Học', 'Tiếng Đức'),
(75, 'D32', 'Toán Học', 'Sinh Học', 'Tiếng Nga'),
(76, 'D33', 'Toán Học', 'Sinh Học', 'Tiếng Nhật'),
(77, 'D34', 'Toán Học', 'Sinh Học', 'Tiếng Pháp'),
(78, 'D35', 'Toán Học', 'Sinh Học', 'Tiếng Trung'),
(79, 'D41', 'Ngữ Văn', 'Địa Lý', 'Tiếng Đức'),
(80, 'D42', 'Ngữ Văn', 'Địa Lý', 'Tiếng Nga'),
(81, 'D43', 'Ngữ Văn', 'Địa Lý', 'Tiếng Nhật'),
(82, 'D44', 'Ngữ Văn', 'Địa Lý', 'Tiếng Pháp'),
(83, 'D45', 'Ngữ Văn', 'Địa Lý', 'Tiếng Trung'),
(84, 'D52', 'Ngữ Văn', 'Vật Lí', 'Tiếng Nga'),
(85, 'D54', 'Ngữ Văn', 'Vật Lí', 'Tiếng Pháp'),
(86, 'D55', 'Ngữ Văn', 'Vật Lí', 'Tiếng Trung'),
(87, 'D61', 'Ngữ Văn', 'Lịch Sử', 'Tiếng Đức'),
(88, 'D62', 'Ngữ Văn', 'Lịch Sử', 'Tiếng Nga'),
(89, 'D63', 'Ngữ Văn', 'Lịch Sử', 'Tiếng Nhật'),
(90, 'D64', 'Ngữ Văn', 'Lịch Sử', 'Tiếng Pháp'),
(91, 'D65', 'Ngữ Văn', 'Lịch Sử', 'Tiếng Trung'),
(92, 'D66', 'Ngữ Văn', 'Giáo Dục Công Dân', 'Tiếng Anh'),
(93, 'D68', 'Ngữ Văn', 'Giáo Dục Công Dân', 'Tiếng Nga'),
(94, 'D69', 'Ngữ Văn', 'Giáo Dục Công Dân', 'Tiếng Nhật'),
(95, 'D70', 'Ngữ Văn', 'Giáo Dục Công Dân', 'Tiếng Pháp'),
(96, 'D72', 'Ngữ Văn', 'Khoa Học Tự Nhiên', 'Tiếng Anh'),
(97, 'D73', 'Ngữ Văn', 'Khoa Học Tự Nhiên', 'Tiếng Đức'),
(98, 'D74', 'Ngữ Văn', 'Khoa Học Tự Nhiên', 'Tiếng Nga'),
(99, 'D75', 'Ngữ Văn', 'Khoa Học Tự Nhiên', 'Tiếng Nhật'),
(100, 'D76', 'Ngữ Văn', 'Khoa Học Tự Nhiên', 'Tiếng Pháp'),
(101, 'D77', 'Ngữ Văn', 'Khoa Học Tự Nhiên', 'Tiếng Trung'),
(102, 'D78', 'Ngữ Văn', 'Khoa Học Xã Hội', 'Tiếng Anh'),
(103, 'D79', 'Ngữ Văn', 'Khoa Học Xã Hội', 'Tiếng Đức'),
(104, 'D80', 'Ngữ Văn', 'Khoa Học Xã Hội', 'Tiếng Nga'),
(105, 'D81', 'Ngữ Văn', 'Khoa Học Xã Hội', 'Tiếng Nhật'),
(106, 'D82', 'Ngữ Văn', 'Khoa Học Xã Hội', 'Tiếng Pháp'),
(107, 'D83', 'Ngữ Văn', 'Khoa Học Xã Hội', 'Tiếng Trung'),
(108, 'D84', 'Toán Học', 'Giáo Dục Công Dân', 'Tiếng Anh'),
(109, 'D85', 'Toán Học', 'Giáo Dục Công Dân', 'Tiếng Đức'),
(110, 'D86', 'Toán Học', 'Giáo Dục Công Dân', 'Tiếng Nga'),
(111, 'D87', 'Toán Học', 'Giáo Dục Công Dân', 'Tiếng Pháp'),
(112, 'D88', 'Toán Học', 'Giáo Dục Công Dân', 'Tiếng Nhật'),
(113, 'D90', 'Toán Học', 'Khoa Học Tự Nhiên', 'Tiếng Anh'),
(114, 'D91', 'Toán Học', 'Khoa Học Tự Nhiên', 'Tiếng Pháp'),
(115, 'D92', 'Toán Học', 'Khoa Học Tự Nhiên', 'Tiếng Đức'),
(116, 'D93', 'Toán Học', 'Khoa Học Tự Nhiên', 'Tiếng Nga'),
(117, 'D94', 'Toán Học', 'Khoa Học Tự Nhiên', 'Tiếng Nhật'),
(118, 'D95', 'Toán Học', 'Khoa Học Tự Nhiên', 'Tiếng Trung'),
(119, 'D96', 'Toán Học', 'Khoa Học Xã Hội', 'Tiếng Anh'),
(120, 'D97', 'Toán Học', 'Khoa Học Xã Hội', 'Tiếng Pháp'),
(121, 'D98', 'Toán Học', 'Khoa Học Xã Hội', 'Tiếng Đức'),
(122, 'D99', 'Toán Học', 'Khoa Học Xã Hội', 'Tiếng Nga'),
(123, 'H00', 'Ngữ Văn', 'Năng Khiếu Vẽ Nghệ Thuật 1', 'Năng Khiếu Vẽ Nghệ Thuật 2'),
(124, 'H01', 'Toán Học', 'Ngữ Văn', 'Vữ'),
(125, 'H02', 'Toán học', 'Vẽ Hình Họa Mỹ Thuật', 'Vẽ Trang Trí Màu'),
(126, 'H03', 'Toán Học', 'Khoa Học Tự Nhiên', 'Vẽ Năng Khiếu'),
(127, 'H04', 'Toán Học', 'Tiếng Anh', 'Vẽ Năng Khiếu'),
(128, 'H05', 'Ngữ Văn', 'Khoa Học Xã Hội', 'Vẽ Năng Khiếu'),
(129, 'H06', 'Ngữ Văn', 'Tiếng Anh', 'Vẽ Mỹ Thuật'),
(130, 'H07', 'Toán Học', 'Hình Họa', 'Trang Trí'),
(131, 'H08', 'Ngữ Văn', 'Lịch Sử', 'Vẽ Mỹ Thuật'),
(132, 'K01', 'Toán Học', 'Tiếng Anh', 'Tin Học'),
(133, 'M00', 'Ngữ Văn', 'Toán Học', 'Đọc Diễn Cảm - Hát'),
(134, 'M01', 'Ngữ Văn', 'Lịch Sử', 'Năng Khiếu'),
(135, 'M02', 'Toán Học', 'Năng Khiếu 1', 'Năng Khiếu 2'),
(136, 'M03', 'Ngữ Văn', 'Năng Khiếu 1', 'Năng Khiếu 2'),
(137, 'M04', 'Toán Học', 'Đọc Diễn Cảm', 'Hát - Múa'),
(138, 'M09', 'Toán Học', 'Năng Khiếu Mầm Non 1', 'Năng Khiếu Mầm Non 2'),
(139, 'M10', 'Toán Học', 'Tiếng Anh', 'Năng Khiếu 1'),
(140, 'M11', 'Ngữ Văn', 'Năng Khiếu Báo Chí', 'Tiếng Anh'),
(141, 'M13', 'Toán Học', 'Sinh Học', 'Năng Khiếu'),
(142, 'M14', 'Ngữ Văn', 'Năng Khiếu Báo Chí', 'Toán Học'),
(143, 'M15', 'Ngữ Văn', 'Năng Khiếu Báo Chí', 'Tiếng Anh'),
(144, 'M16', 'Ngữ Văn', 'Năng Khiếu Báo Chí', 'Vật Lí'),
(145, 'M17', 'Ngữ Văn', 'Năng Khiếu Báo Chí', 'Lích Sử'),
(146, 'M18', 'Ngữ Văn', 'Năng Khiếu Ảnh Báo Chí', 'Toán Học'),
(147, 'M19', 'Ngữ Văn', 'Năng Khiếu Ảnh Báo Chí', 'Tiếng Anh'),
(148, 'M20', 'Ngữ Văn', 'Năng Khiếu Ảnh Báo Chí', 'Vật Lí'),
(149, 'M21', 'Ngữ Văn', 'Năng Khiếu Ảnh Báo Chí', 'Lịch Sử'),
(150, 'M22', 'Ngữ Văn', 'Năng Khiếu Quay Phim Truyền Hình', 'Toán Học'),
(151, 'M23', 'Ngữ Văn', 'Năng Khiếu Quay Phim Truyền Hình', 'Tiếng Anh'),
(152, 'M24', 'Ngữ Văn', 'Năng Khiếu Quay Phim Truyền Hình', 'Vật Lí'),
(153, 'M25', 'Ngữ Văn', 'Năng Khiếu Quay Phim Truyền Hình', 'Lích Sử'),
(154, 'N00', 'Ngữ Văn', 'Năng Khiếu Âm Nhạc 1', 'Năng Khiếu Âm Nhạc 2'),
(155, 'N01', 'Ngữ Văn', 'Xướng Âm', 'Biểu Diễn Nghệ Thuật'),
(156, 'N02', 'Ngữ Văn', 'Ký Xướng Âm', 'Hát Hoặc Biểu Diễn Nhạc Cụ'),
(157, 'N03', 'Ngữ Văn', 'Ghi Âm - Xướng Âm', 'Chuyên Môn'),
(158, 'N04', 'Ngữ Văn', 'Năng Khiếu Thuyết Trình', 'Năng Khiếu'),
(159, 'N05', 'Ngữ Văn', 'Xây Dựng Kích Bản Sự Kiện', 'Năng Khiếu'),
(160, 'N08', 'Ngữ Văn', 'Hòa Thanh', 'Phát Triển Chủ Đề Và Pgổ Thơ'),
(161, 'N09', 'Ngữ Văn', 'Hòa Thanh', 'Chỉ Huy Tại Chỗ'),
(162, 'R00', 'Ngữ Văn', 'Lích Sử', 'Năng Khiếu Báo Chí'),
(163, 'R01', 'Ngữ Văn', 'Địa Lý', 'Năng Khiếu Biểu Diễn Nghệ Thuật'),
(164, 'R02', 'Ngữ Văn', 'Toán Học', 'Năng Khiếu Biểu Diễn Nghệ Thuật'),
(165, 'R04', 'Ngữ Văn', 'Năng Khiếu Biểu Diễn Nghệ Thuật', 'Năng khiếu Kiến thức Văn Hóa - Xã Hội - Nghệ Thuật'),
(166, 'R05', 'Ngữ Văn', 'Tiếng Anh', 'Năng Khiếu Kiến Thức Truyền Thông'),
(167, 'S00', 'Ngữ Văn', 'Năng Khiếu Sân Khấu Điện Ảnh 1', 'Năng Khiếu Sân Khấu Điện Ảnh 2'),
(168, 'S01', 'Toán Học', 'Năng Khiếu 1', 'Năng Khiếu 2'),
(169, 'T00', 'Toán Học', 'Sinh Học', 'Năng Khiếu Thể Dục Thể Thao'),
(170, 'T01', 'Toán Học', 'Ngữ Văn', 'Năng Khiếu Thể Dục Thể Thao'),
(171, 'T02', 'Ngữ Văn', 'Sinh Học', 'Năng Khiếu Thể Dục Thể Thao'),
(172, 'T03', 'Ngữ Văn', 'Địa Lý', 'Năng Khiếu Thể Dục Thể Thao'),
(173, 'T04', 'Toán Học', 'Vật Lí', 'Năng Khiếu Thể Dục Thể Thao'),
(174, 'T05', 'Ngữ Văn', 'Giáo Dục Công Dân', 'Năng Khiếu'),
(175, 'V00', 'Toán Học', 'Vật Lí', 'Vẽ Hình Họa Mỹ Thuật'),
(176, 'V01', 'Toán Học', 'Ngữ Văn', 'Vẽ Hình Họa Mỹ Thuật'),
(177, 'V02', 'Vẽ Mỹ Thuật', 'Toán Học', 'Tiếng Anh'),
(178, 'V03', 'Vẽ Mỹ Thuật', 'Toán Học', 'Hóa Học'),
(179, 'V04', 'Vẽ Mỹ Thuật', 'Ngữ Văn', 'Vật Lí'),
(180, 'V06', 'Vẽ Mỹ Thuật', 'Toán Học', 'Địa Lý'),
(181, 'V07', 'Vẽ Mỹ Thuật', 'Toán Học', 'Tiếng Đức'),
(182, 'V08', 'Vẽ Mỹ Thuật', 'Toán Học', 'Tiếng Nga'),
(183, 'V09', 'Vẽ Mỹ Thuật', 'Toán Học', 'Tiếng Nhật'),
(184, 'V10', 'Vẽ Mỹ Thuật', 'Toán Học', 'Tiếng Pháp'),
(185, 'V11', 'Vẽ Mỹ Thuật', 'Toán Học', 'Tiếng Trung');
